[package]
name = "rodio"
version = "0.11.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/RustAudio/rodio"
documentation = "http://docs.rs/rodio"
edition = "2018"

[dependencies]
claxon = { version = "0.4.2", optional = true }
cpal = { git = "https://github.com/amethyst/cpal", branch = "wasm" }
hound = { version = "3.3.1", optional = true }
lewton = { version = "0.10", optional = true }
minimp3 = { version = "0.3.2", optional = true }

[features]
default = ["flac", "vorbis", "wav", "mp3"]

flac = ["claxon"]
vorbis = ["lewton"]
wav = ["hound"]
mp3 = ["minimp3"]
